import '../../styles/globals.css';
import Footer from '@/components/footer/Footer';
import Navbar from '@/components/header/Navbar';
import dynamic from 'next/dynamic';
import { Analytics } from '@vercel/analytics/react';
import { lateef, cairo, tajawal } from '@/lib/fonts';
import { Toaster } from '@/components/ui/toaster';
// import NextTopLoader from 'nextjs-toploader';
// import InternetStatus from '@/components/shared/internet/InternetStatus';
const Providers = dynamic(() => import('@/Providers/Provider'));
export const metadata = {
    title: 'EazyCode',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'ar' }];
}

export default function RootLayout({ children, params }) {
    return (
        <html
            lang={params.lang}
            dir={params.lang === 'ar' ? 'rtl' : 'ltr'}
            style={{ colorScheme: 'dark' }}
            className='dark'
        >
            <body
                className={`${cairo.variable} ${lateef.variable}  ${tajawal.variable}    h-[dvh] `}
            >
                <section id='childrenxx'>
                    <Providers
                        attribute='class'
                        defaultTheme='dark'
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className='grid   h-[calc(100dvh)] grid-rows-[auto_minmax(0,1fr)] '>
                            <div className='row-span-1'>
                                <Navbar lang={params.lang} />
                            </div>
                            {/* <NextTopLoader
                                color='#2299DD'
                                initialPosition={0.08}
                                crawlSpeed={200}
                                height={8}
                                crawl={true}
                                showSpinner={true}
                                easing='ease'
                                speed={200}
                                shadow='0 0 10px #2299DD,0 0 5px #2299DD'
                            /> */}
                            {/* <InternetStatus /> */}
                            <div> {children}</div>
                            <div>
                                <Footer lang={params.lang} />
                            </div>
                        </div>
                    </Providers>
                    <Toaster />
                    <Analytics />
                </section>
            </body>
        </html>
    );
}
